# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: RCharan.wiki
PackageVersion: "1.0"
PackageLocale: en-US
Publisher: R Charan
PackageName: wiki
License: MIT License
ShortDescription: wiki Setup
ManifestType: defaultLocale
ManifestVersion: 1.6.0
